Repository KDT3-Final-6/final-project-BE, pull requests merged in 2023-04, with the labels that each got.

#105 Feat/password check, hobby
  travel/src/main/java/com/travel/auth/controller/AuthController.java
  travel/src/main/java/com/travel/auth/dto/request/MemberRequestDto.java
  travel/src/main/java/com/travel/auth/service/MemberService.java
  travel/src/main/java/com/travel/global/config/SecurityConfig.java
  travel/src/main/java/com/travel/member/controller/MemberController.java
  travel/src/main/java/com/travel/member/dto/requestDTO/MemberModifyRequestDTO.java
  travel/src/main/java/com/travel/member/dto/requestDTO/PasswordCheckDTO.java
  travel/src/main/java/com/travel/member/dto/responseDTO/MemberResponseDTO.java
  travel/src/main/java/com/travel/member/entity/Hobby.java
  travel/src/main/java/com/travel/member/entity/Member.java
  travel/src/main/java/com/travel/member/service/MemberService.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Feature, Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#107 Feature/review 리뷰 CRUD 기능 구현
  travel/src/main/java/com/travel/global/config/SecurityConfig.java
  travel/src/main/java/com/travel/order/dto/response/OrderResponseDTO.java
  travel/src/main/java/com/travel/order/service/impl/OrderServiceImpl.java
  travel/src/main/java/com/travel/post/controller/ReviewController.java
  travel/src/main/java/com/travel/post/dto/request/ReviewCreateRequestDTO.java
  travel/src/main/java/com/travel/post/dto/request/ReviewUpdateRequestDTO.java
  travel/src/main/java/com/travel/post/dto/response/ReviewListMemberDTO.java
  travel/src/main/java/com/travel/post/dto/response/ReviewListProductDTO.java
  travel/src/main/java/com/travel/post/entity/Post.java
  travel/src/main/java/com/travel/post/entity/ReviewPost.java
  travel/src/main/java/com/travel/post/entity/Scope.java
  travel/src/main/java/com/travel/post/repository/ReviewRepository.java
  travel/src/main/java/com/travel/post/service/ReviewService.java
  travel/src/main/java/com/travel/post/service/impl/ReviewServiceImpl.java
  travel/src/main/java/com/travel/product/entity/PurchasedProduct.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend, Type: Configuration

#110 Feat/admin member list
  travel/src/main/java/com/travel/admin/controller/AdminController.java
  travel/src/main/java/com/travel/admin/dto/responseDTO/MemberListDTO.java
  travel/src/main/java/com/travel/admin/service/AdminService.java
  travel/src/main/java/com/travel/admin/service/impl/AdminServiceImpl.java
  travel/src/main/java/com/travel/member/repository/MemberRepository.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#112 bug: 카테고리 검색에서 정렬 기준없애면 500에러뜨는 현상 해결
  travel/src/main/java/com/travel/search/service/impl/SearchServiceImpl.java
Labels: Type: Bug, Status: Completed, Priority: High, For: API, For: Backend

#113 Feat/admin memberlist Refactor/ signup
  travel/src/main/java/com/travel/admin/controller/AdminController.java
  travel/src/main/java/com/travel/admin/dto/responseDTO/MemberListDTO.java
  travel/src/main/java/com/travel/admin/service/AdminService.java
  travel/src/main/java/com/travel/admin/service/impl/AdminServiceImpl.java
  travel/src/main/java/com/travel/auth/dto/request/MemberRequestDto.java
  travel/src/main/java/com/travel/auth/service/MemberService.java
  travel/src/main/java/com/travel/member/entity/Hobby.java
  travel/src/main/java/com/travel/member/entity/Member.java
Labels: Type: Feature, Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#116 Bug/search 카테고리 검색 사이즈 무한으로 나오는 현상 수정, 상품 추천 기능 구현
  travel/src/main/java/com/travel/global/config/SecurityConfig.java
  travel/src/main/java/com/travel/member/entity/Hobby.java
  travel/src/main/java/com/travel/product/controller/ProductController.java
  travel/src/main/java/com/travel/search/service/SearchService.java
  travel/src/main/java/com/travel/search/service/impl/SearchServiceImpl.java
Labels: Type: Bug, Type: Feature, Status: Completed, Priority: High, For: API, For: Backend

#118 Feature/product 연관 상품 추천 기능 구현
  travel/src/main/java/com/travel/product/controller/ProductController.java
  travel/src/main/java/com/travel/search/service/SearchService.java
  travel/src/main/java/com/travel/search/service/impl/SearchServiceImpl.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#119 Feature/survey 설문조사 기능 추가 및 리팩토링
  travel/src/main/java/com/travel/admin/controller/AdminController.java
  travel/src/main/java/com/travel/cart/controller/CartController.java
  travel/src/main/java/com/travel/global/config/SecurityConfig.java
  travel/src/main/java/com/travel/member/entity/Member.java
  travel/src/main/java/com/travel/member/exception/MemberExceptionType.java
  travel/src/main/java/com/travel/order/controller/OrderController.java
  travel/src/main/java/com/travel/post/controller/QnAController.java
  travel/src/main/java/com/travel/post/controller/ReviewController.java
  travel/src/main/java/com/travel/product/dto/response/CategoriesInProduct.java
  travel/src/main/java/com/travel/product/dto/response/CategoryListGetResponseDTO.java
  travel/src/main/java/com/travel/product/entity/Category.java
  travel/src/main/java/com/travel/survey/Controller/SurveyController.java
  travel/src/main/java/com/travel/survey/dto/SurveyDTO.java
  travel/src/main/java/com/travel/survey/entity/Companion.java
  travel/src/main/java/com/travel/survey/entity/Gender.java
  travel/src/main/java/com/travel/survey/entity/Group.java
  travel/src/main/java/com/travel/survey/entity/Hobby.java
  travel/src/main/java/com/travel/survey/entity/Religion.java
  travel/src/main/java/com/travel/survey/entity/Season.java
  travel/src/main/java/com/travel/survey/entity/Survey.java
  travel/src/main/java/com/travel/survey/repository/SurveyRepository.java
  travel/src/main/java/com/travel/survey/service/SurveyService.java
  travel/src/main/java/com/travel/wishlist/controller/WishlistController.java
Labels: Type: Feature, Type: Refactor, Status: In Progress, Priority: Medium, For: API, For: Backend

#121 Feat/admin delete member
  travel/src/main/java/com/travel/admin/controller/AdminController.java
  travel/src/main/java/com/travel/admin/dto/responseDTO/MemberListDTO.java
  travel/src/main/java/com/travel/admin/service/AdminService.java
  travel/src/main/java/com/travel/admin/service/impl/AdminServiceImpl.java
  travel/src/main/java/com/travel/member/repository/MemberRepository.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#129 Feature/post QnA 리스트 ResponseDTO에 답변 달린 날짜 필드, 전체 후기 리스트 조회 ResponseDTO에 멤버 닉네임 필드추가
  travel/src/main/java/com/travel/post/dto/response/QnAAdminResponseDTO.java
  travel/src/main/java/com/travel/post/dto/response/QnAResponseDTO.java
  travel/src/main/java/com/travel/post/dto/response/ReviewListDTO.java
  travel/src/main/java/com/travel/post/entity/AnswerPost.java
  travel/src/main/java/com/travel/post/entity/QnAPost.java
  travel/src/main/java/com/travel/post/entity/QnAProductPost.java
  travel/src/main/java/com/travel/post/entity/ReviewPost.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#133 Fix/member
  travel/src/main/java/com/travel/admin/dto/responseDTO/MemberDetailInfoDTO.java
  travel/src/main/java/com/travel/auth/dto/request/MemberRequestDto.java
  travel/src/main/java/com/travel/auth/service/MemberService.java
  travel/src/main/java/com/travel/member/dto/requestDTO/MemberModifyRequestDTO.java
  travel/src/main/java/com/travel/member/dto/responseDTO/MemberResponseDTO.java
  travel/src/main/java/com/travel/member/entity/Member.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Bug, Status: Completed, Priority: Medium, For: API, For: Backend

#137 Bug/cart 주문, 장바구니 productId를 받는 로직, 페이징 처리 안되는 현상 수정
  travel/src/main/java/com/travel/cart/dto/request/CartAddDTO.java
  travel/src/main/java/com/travel/cart/dto/request/CartUpdateDTO.java
  travel/src/main/java/com/travel/cart/service/impl/CartServiceImpl.java
  travel/src/main/java/com/travel/global/exception/GlobalExceptionType.java
  travel/src/main/java/com/travel/order/dto/request/OrderCreateDTO.java
  travel/src/main/java/com/travel/order/service/impl/OrderServiceImpl.java
  travel/src/main/java/com/travel/post/service/impl/QnAServiceImpl.java
  travel/src/main/java/com/travel/post/service/impl/ReviewServiceImpl.java
  travel/src/main/java/com/travel/search/service/impl/SearchServiceImpl.java
  travel/src/main/java/com/travel/wishlist/service/impl/WishlistServiceImpl.java
Labels: Type: Bug, Status: Completed, Priority: High, For: API, For: Backend

#138 Feature/hotfix 토큰, 이미지, 큐레이션 관련 핫픽스
  travel/src/main/java/com/travel/auth/jwt/JwtTokenProvider.java
  travel/src/main/java/com/travel/curation/repository/CurationRepositoryCustomImpl.java
  travel/src/main/java/com/travel/image/service/FileUploadService.java
Labels: Type: Feature, Type: Refactor, Status: In Progress, Priority: Critical, For: API, For: Backend

#146 Feature/refactor wishlist 하트 개수, 눌렀는지 여부 활용 로직 추가
  travel/src/main/java/com/travel/admin/controller/AdminController.java
  travel/src/main/java/com/travel/curation/controller/CurationController.java
  travel/src/main/java/com/travel/curation/service/CurationService.java
  travel/src/main/java/com/travel/product/controller/ProductController.java
  travel/src/main/java/com/travel/product/dto/response/ProductCategoryToProductPage.java
  travel/src/main/java/com/travel/product/dto/response/ProductDetailGetResponseDTO.java
  travel/src/main/java/com/travel/product/dto/response/ProductListGetResponseDTO.java
  travel/src/main/java/com/travel/product/service/ProductService.java
  travel/src/main/java/com/travel/search/service/impl/SearchServiceImpl.java
Labels: Type: Feature, Type: Refactor, Status: In Progress, Priority: Medium, For: API, For: Backend

#147 refactor: 연관 상품 로직 수정
  travel/src/main/java/com/travel/search/service/impl/SearchServiceImpl.java
Labels: Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#150 Fix/delete member
  travel/src/main/java/com/travel/auth/enums/TokenType.java
  travel/src/main/java/com/travel/auth/jwt/JwtTokenProvider.java
  travel/src/main/java/com/travel/auth/service/MemberService.java
  travel/src/main/java/com/travel/member/controller/MemberController.java
  travel/src/main/java/com/travel/member/dto/requestDTO/DeleteMemberDTO.java
  travel/src/main/java/com/travel/member/service/MemberService.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#152 refactor: QnA 문의유형 환불 이름 변경
  travel/src/main/java/com/travel/post/entity/InquiryType.java
Labels: Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#155 Refactor/cart 장바구니 삭제 쿼리 파라미터로 받도록 변경, MissingServletRequestParameterException 핸들러 추가, Validation 예외 처리 수정
  travel/src/main/java/com/travel/cart/controller/CartController.java
  travel/src/main/java/com/travel/cart/dto/request/CartDeleteDTO.java
  travel/src/main/java/com/travel/cart/dto/request/CartDeleteListDTO.java
  travel/src/main/java/com/travel/cart/exception/CartExceptionType.java
  travel/src/main/java/com/travel/cart/service/CartService.java
  travel/src/main/java/com/travel/cart/service/impl/CartServiceImpl.java
  travel/src/main/java/com/travel/global/exception/CustomExceptionHandler.java
Labels: Type: Feature, Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#156 Refactor/login
  travel/src/main/java/com/travel/auth/controller/AuthController.java
  travel/src/main/java/com/travel/auth/dto/request/MemberRequestDto.java
  travel/src/main/java/com/travel/auth/dto/response/MemberResponseDto.java
  travel/src/main/java/com/travel/auth/service/MemberService.java
Labels: Type: Refactor, Status: Completed, Priority: Low, For: API, For: Backend

#157 Fix/delete member
  travel/src/main/java/com/travel/member/controller/MemberController.java
  travel/src/main/java/com/travel/member/dto/requestDTO/DeleteMemberDTO.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Refactor, Status: Completed, Priority: Low, For: API, For: Backend

#161 Refactor/order 리스트 내림차순으로 출력하도록 변경
  travel/src/main/java/com/travel/order/service/impl/OrderServiceImpl.java
  travel/src/main/java/com/travel/post/service/impl/QnAServiceImpl.java
  travel/src/main/java/com/travel/post/service/impl/ReviewServiceImpl.java
Labels: Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#162 Refactor: RequestParam 리스트로 받게 변경, 타임존 설정, product list id 내림차순으로 변경
  travel/src/main/java/com/travel/TravelApplication.java
  travel/src/main/java/com/travel/curation/controller/CurationController.java
  travel/src/main/java/com/travel/product/repository/product/ProductRepository.java
  travel/src/main/java/com/travel/product/repository/product/ProductRepositoryCustomImpl.java
  travel/src/main/java/com/travel/product/service/ProductService.java
Labels: Type: Bug, Type: Refactor, Status: In Progress, Priority: Critical, For: API, For: Backend

#166 Refactor/login, listdesc
  travel/src/main/java/com/travel/admin/service/impl/AdminServiceImpl.java
  travel/src/main/java/com/travel/auth/dto/response/MemberResponseDto.java
  travel/src/main/java/com/travel/auth/service/MemberService.java
  travel/src/main/java/com/travel/member/dto/responseDTO/MemberResponseDTO.java
  travel/src/main/java/com/travel/member/repository/MemberRepository.java
Labels: Type: Refactor, Status: Completed, Priority: Low, For: API, For: Backend

#168 Feat/review 삭제된 리뷰는 리스트 출력에서 제외 시키는 로직, 구매한 상품의 Review 생성을 하나만 할 수 있도록 로직 추가
  travel/src/main/java/com/travel/order/repository/OrderRepository.java
  travel/src/main/java/com/travel/post/exception/PostExceptionType.java
  travel/src/main/java/com/travel/post/service/impl/ReviewServiceImpl.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#169 Feat/order 비회원 계좌이체로 결제시 메일로 계좌번호랑 구매내역 보내는 기능 구현
  travel/build.gradle
  travel/src/main/java/com/travel/global/exception/CustomExceptionHandler.java
  travel/src/main/java/com/travel/nonmember/controller/NonMembersController.java
  travel/src/main/java/com/travel/nonmember/service/MailService.java
  travel/src/main/java/com/travel/nonmember/service/impl/MailServiceImpl.java
  travel/src/main/java/com/travel/order/dto/request/OrderNonMemberCreateDTO.java
  travel/src/main/java/com/travel/order/repository/OrderRepository.java
  travel/src/main/java/com/travel/order/service/OrderService.java
  travel/src/main/java/com/travel/order/service/impl/OrderServiceImpl.java
  travel/src/main/resources/templates/mail.html
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#170 Fix/password check
  travel/src/main/java/com/travel/member/controller/MemberController.java
  travel/src/main/java/com/travel/member/service/MemberService.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Bug, Status: Completed, Priority: Medium, For: API, For: Backend

#171 fix/admin member list
  travel/src/main/java/com/travel/admin/service/impl/AdminServiceImpl.java
Labels: Type: Bug, Status: Completed, Priority: Medium, For: API, For: Backend

#173 refactor: 리스트 내림차순으로 출력하도록 변경
  travel/src/main/java/com/travel/cart/service/impl/CartServiceImpl.java
Labels: Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#174 fix token
  travel/src/main/java/com/travel/auth/service/MemberService.java
Labels: Type: Bug, Status: Completed, Priority: High, For: API, For: Backend

#176 Fix/member update
  travel/src/main/java/com/travel/member/controller/MemberController.java
  travel/src/main/java/com/travel/member/dto/requestDTO/MemberModifyRequestDTO.java
  travel/src/main/java/com/travel/member/dto/requestDTO/PasswordCheckDTO.java
  travel/src/main/java/com/travel/member/entity/Member.java
  travel/src/main/java/com/travel/member/service/MemberService.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Bug, Type: Refactor, Priority: Medium, For: API, For: Backend

#178 Refactor/wishlist 리스트 내림차순으로 출력하도록 변경, 1대1 문의에서 사용할 구매내역 리스트 조회 기능 구현
  travel/src/main/java/com/travel/order/controller/OrderController.java
  travel/src/main/java/com/travel/order/dto/response/OrderByQnAResponseDTO.java
  travel/src/main/java/com/travel/order/service/OrderService.java
  travel/src/main/java/com/travel/order/service/impl/OrderServiceImpl.java
  travel/src/main/java/com/travel/wishlist/service/impl/WishlistServiceImpl.java
Labels: Type: Feature, Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#179 Refactor/order Order 리스트(관리자용) 내림차순으로 출력하도록 변경
  travel/src/main/java/com/travel/order/service/impl/OrderServiceImpl.java
Labels: Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#183 Refactor/wishlist 위시리스트 삭제 기능 수정
  travel/src/main/java/com/travel/wishlist/controller/WishlistController.java
  travel/src/main/java/com/travel/wishlist/repository/WishlistRepository.java
  travel/src/main/java/com/travel/wishlist/service/WishlistService.java
  travel/src/main/java/com/travel/wishlist/service/impl/WishlistServiceImpl.java
Labels: Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#181 Feat/find email&pw
  travel/src/main/java/com/travel/global/config/SecurityConfig.java
  travel/src/main/java/com/travel/member/controller/MemberController.java
  travel/src/main/java/com/travel/member/dto/requestDTO/FindMemberDTO.java
  travel/src/main/java/com/travel/member/repository/MemberRepository.java
  travel/src/main/java/com/travel/member/service/MemberService.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
  travel/src/main/java/com/travel/member/util/PasswordUtils.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#184 fix/memberInfo 성별추가
  travel/src/main/java/com/travel/member/dto/responseDTO/MemberResponseDTO.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Refactor, Status: Completed, Priority: Low, For: API, For: Backend

#186 Fix/member update
  travel/src/main/java/com/travel/member/controller/MemberController.java
  travel/src/main/java/com/travel/member/dto/requestDTO/MemberModifyRequestDTO.java
  travel/src/main/java/com/travel/member/entity/Member.java
  travel/src/main/java/com/travel/member/service/MemberService.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Bug, Status: Completed, Priority: Medium, For: API, For: Backend

#187 refactor/member 정규식 적용
  travel/src/main/java/com/travel/auth/dto/request/MemberRequestDto.java
  travel/src/main/java/com/travel/member/dto/requestDTO/MemberModifyRequestDTO.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#189 Refactor/order 주문 리스트(관리자용) ResponseDTO 및 로직 수정
  travel/src/main/java/com/travel/order/dto/response/OrderAdminResponseDTO.java
  travel/src/main/java/com/travel/order/dto/response/OrderListAdminResponseDTO.java
  travel/src/main/java/com/travel/order/service/impl/OrderServiceImpl.java
  travel/src/main/java/com/travel/product/entity/PurchasedProduct.java
Labels: Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#190 Fix/member
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#192 bug: #191 비회원 주문에서 멤버가 저장이 안되는 현상
  travel/src/main/java/com/travel/member/entity/Member.java
Labels: Type: Bug, Status: Completed, Priority: High, For: API, For: Backend

#194 Refactor/order 주문 리스트(관리자용) ResponseDTO 수정
  travel/src/main/java/com/travel/order/dto/response/OrderAdminResponseDTO.java
  travel/src/main/java/com/travel/product/entity/PurchasedProduct.java
Labels: Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#196 Bug/order: 비회원 주문시 같은 이메일로 주문할 때마다 멤버 생성되는 현상 수정
  travel/src/main/java/com/travel/order/service/impl/OrderServiceImpl.java
Labels: Type: Bug, Status: Completed, Priority: High, For: API, For: Backend

#199 Fix/member 양방향 참조에서 충돌일어나는 현상 수정, 관리자가 회원 정보 출력할때 요구값 수정 및 고침
  travel/src/main/java/com/travel/admin/dto/responseDTO/MemberListDTO.java
  travel/src/main/java/com/travel/admin/service/impl/AdminServiceImpl.java
  travel/src/main/java/com/travel/order/entity/Order.java
Labels: Type: Bug, Status: Completed, Priority: Medium, For: API, For: Backend

#200 fix/adminMemberInfo 오류로 인한 부분 삭제
  travel/src/main/java/com/travel/admin/dto/responseDTO/MemberDetailInfoDTO.java
Labels: Type: Bug, Status: Completed, Priority: High, For: API, For: Backend

#203 fix/changeToAdmin 관리자로 변경 요청했을때 관리자여도 계속 관리자가 추가되는 문제 수정
  travel/src/main/java/com/travel/admin/service/impl/AdminServiceImpl.java
Labels: Type: Bug, Status: Completed, Priority: Medium, For: API, For: Backend

#205 Refactor/search QnA 검색 결과 리스트 내림차순으로 변경
  travel/src/main/java/com/travel/search/service/SearchService.java
  travel/src/main/java/com/travel/search/service/impl/SearchServiceImpl.java
Labels: Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend
