Repository KDT3-Final-6/final-project-BE, pull requests merged in 2023-03, with the labels that each got.

#25 Feature/product #8 #24 이슈와 관련된 사항들 구현
  travel/src/main/java/com/travel/admin/controller/AdminController.java
  travel/src/main/java/com/travel/product/controller/ProductController.java
  travel/src/main/java/com/travel/product/dto/response/ProductCategoryToProductPage.java
  travel/src/main/java/com/travel/product/dto/response/ProductDetailGetResponseDTO.java
  travel/src/main/java/com/travel/product/entity/CategoryEnum.java
  travel/src/main/java/com/travel/product/entity/PeriodOption.java
  travel/src/main/java/com/travel/product/entity/Product.java
  travel/src/main/java/com/travel/product/entity/ProductCategory.java
  travel/src/main/java/com/travel/product/exception/ProductExceptionType.java
  travel/src/main/java/com/travel/product/repository/CategoryRepository.java
  travel/src/main/java/com/travel/product/repository/ProductCategoryRepository.java
  travel/src/main/java/com/travel/product/repository/product/ProductRepositoryCustomImpl.java
  travel/src/main/java/com/travel/product/service/ProductService.java
  travel/src/main/java/com/travel/search/controller/SearchController.java
  travel/src/main/java/com/travel/search/service/SearchService.java
Labels: Type: Feature, Status: In Progress, Priority: Medium, For: API, For: Backend

#30 Feature/product 상품 수정, PeriodOption에 Status 추가
  travel/src/main/java/com/travel/admin/controller/AdminController.java
  travel/src/main/java/com/travel/product/dto/request/PeriodOptionDTO.java
  travel/src/main/java/com/travel/product/dto/request/PeriodPostRequestDTO.java
  travel/src/main/java/com/travel/product/dto/request/ProductPatchRequestDTO.java
  travel/src/main/java/com/travel/product/entity/PeriodOption.java
  travel/src/main/java/com/travel/product/entity/Product.java
  travel/src/main/java/com/travel/product/service/ProductService.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#35 Feature/order 검색 기능 구현, 상품 주문 및 주문 내역 조회 기능 수정
  travel/src/main/java/com/travel/admin/controller/AdminController.java
  travel/src/main/java/com/travel/global/exception/GlobalExceptionType.java
  travel/src/main/java/com/travel/order/controller/OrderController.java
  travel/src/main/java/com/travel/order/exception/OrderExceptionType.java
  travel/src/main/java/com/travel/order/repository/OrderRepository.java
  travel/src/main/java/com/travel/order/service/OrderService.java
  travel/src/main/java/com/travel/order/service/impl/OrderServiceImpl.java
  travel/src/main/java/com/travel/product/entity/PeriodOption.java
  travel/src/main/java/com/travel/product/repository/PeriodOptionRepository.java
  travel/src/main/java/com/travel/product/repository/ProductCategoryRepository.java
  travel/src/main/java/com/travel/product/repository/product/ProductRepository.java
  travel/src/main/java/com/travel/search/controller/SearchController.java
  travel/src/main/java/com/travel/search/service/SearchService.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#31 Feature/jwt
  travel/build.gradle
  travel/src/main/java/com/travel/auth/config/RedisRepositoryConfig.java
  travel/src/main/java/com/travel/auth/controller/UsersController.java
  travel/src/main/java/com/travel/auth/dto/ResponseDto.java
  travel/src/main/java/com/travel/auth/dto/UserRequestDto.java
  travel/src/main/java/com/travel/auth/dto/UserResponseDto.java
  travel/src/main/java/com/travel/auth/entity/Users.java
  travel/src/main/java/com/travel/auth/enums/Authority.java
  travel/src/main/java/com/travel/auth/jwt/JwtAuthenticationFilter.java
  travel/src/main/java/com/travel/auth/jwt/JwtTokenProvider.java
  travel/src/main/java/com/travel/auth/lib/Helper.java
  travel/src/main/java/com/travel/auth/repository/UsersRepository.java
  travel/src/main/java/com/travel/auth/security/SecurityUtil.java
  travel/src/main/java/com/travel/auth/security/WebSecurityConfig.java
  travel/src/main/java/com/travel/auth/service/CustomUserDetailsService.java
  travel/src/main/java/com/travel/auth/service/UsersService.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#40 Feature/order 검색 기능 로직 추가, 장바구니 상품 추가 기능 수정
  travel/src/main/java/com/travel/cart/controller/CartController.java
  travel/src/main/java/com/travel/cart/dto/request/CartAddListDTO.java
  travel/src/main/java/com/travel/cart/repository/CartRepository.java
  travel/src/main/java/com/travel/cart/service/CartService.java
  travel/src/main/java/com/travel/cart/service/impl/CartServiceImpl.java
  travel/src/main/java/com/travel/search/service/SearchService.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#44 Feature/ Image, Post Image, Post Entity 만들고 연관관계 매핑
  travel/src/main/java/com/travel/global/entity/BaseEntityWithMemberAndDates.java
  travel/src/main/java/com/travel/image/Image.java
  travel/src/main/java/com/travel/member/entity/Member.java
  travel/src/main/java/com/travel/post/entity/Post.java
  travel/src/main/java/com/travel/product/entity/Product.java
Labels: Type: Feature, Status: In Progress, Priority: Medium, For: Backend

#46 Feature/order 상품 주문, 주문 내역 조회 기능 및 Order 엔티티 수정
  travel/src/main/java/com/travel/order/controller/OrderController.java
  travel/src/main/java/com/travel/order/dto/request/OrderCreateListDTO.java
  travel/src/main/java/com/travel/order/dto/response/OrderListAdminResponseDTO.java
  travel/src/main/java/com/travel/order/dto/response/OrderListResponseDTO.java
  travel/src/main/java/com/travel/order/entity/Order.java
  travel/src/main/java/com/travel/order/entity/PaymentMethod.java
  travel/src/main/java/com/travel/order/repository/OrderRepository.java
  travel/src/main/java/com/travel/order/service/OrderService.java
  travel/src/main/java/com/travel/order/service/impl/OrderServiceImpl.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#37 Refactor/member
  travel/src/main/java/com/travel/auth/controller/MemberController.java
  travel/src/main/java/com/travel/auth/dto/request/MemberRequestDto.java
  travel/src/main/java/com/travel/auth/dto/response/MemberResponseDto.java
  travel/src/main/java/com/travel/auth/entity/Users.java
  travel/src/main/java/com/travel/auth/jwt/JwtTokenProvider.java
  travel/src/main/java/com/travel/auth/repository/UsersRepository.java
  travel/src/main/java/com/travel/auth/security/WebSecurityConfig.java
  travel/src/main/java/com/travel/auth/service/CustomMemberDetailsService.java
  travel/src/main/java/com/travel/auth/service/MemberService.java
  travel/src/main/java/com/travel/global/config/SecurityConfig.java
  travel/src/main/java/com/travel/global/config/SecurityUtil.java
  travel/src/main/java/com/travel/member/entity/Member.java
  travel/src/main/java/com/travel/member/repository/MemberRepository.java
Labels: Type: Refactor, Status: In Progress, Priority: Low, For: API, For: Backend

#53 Feature/member info 회원 정보 조회, 불필요한 부분 수정 및 삭제
  travel/src/main/java/com/travel/auth/controller/AuthController.java
  travel/src/main/java/com/travel/auth/controller/MemberController.java
  travel/src/main/java/com/travel/auth/dto/ResponseDto.java
  travel/src/main/java/com/travel/auth/dto/request/MemberRequestDto.java
  travel/src/main/java/com/travel/auth/jwt/JwtTokenProvider.java
  travel/src/main/java/com/travel/auth/service/MemberService.java
  travel/src/main/java/com/travel/member/controller/MemberController.java
  travel/src/main/java/com/travel/member/dto/responseDTO/MemberResponseDTO.java
  travel/src/main/java/com/travel/member/entity/Member.java
  travel/src/main/java/com/travel/member/service/MemberService.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Feature, Type: Refactor, Status: In Progress, Priority: Medium, For: API, For: Backend

#55 Feature/order Order, Cart 엔티티 수정 및 결제 승인 기능 구현
  travel/src/main/java/com/travel/admin/controller/AdminController.java
  travel/src/main/java/com/travel/cart/entity/Cart.java
  travel/src/main/java/com/travel/cart/repository/CartRepository.java
  travel/src/main/java/com/travel/cart/service/impl/CartServiceImpl.java
  travel/src/main/java/com/travel/order/dto/request/OrderApproveDTO.java
  travel/src/main/java/com/travel/order/dto/response/OrderAdminResponseDTO.java
  travel/src/main/java/com/travel/order/dto/response/OrderResponseDTO.java
  travel/src/main/java/com/travel/order/entity/Order.java
  travel/src/main/java/com/travel/order/entity/OrderStatus.java
  travel/src/main/java/com/travel/order/service/OrderService.java
  travel/src/main/java/com/travel/order/service/impl/OrderServiceImpl.java
  travel/src/main/java/com/travel/product/entity/Product.java
  travel/src/main/java/com/travel/product/entity/PurchasedProduct.java
Labels: Type: Feature, Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#61 Feature/product PeriodOption에 필드 추가, dto 추가 생성
  travel/src/main/java/com/travel/product/dto/request/PeriodOptionDTO.java
  travel/src/main/java/com/travel/product/dto/request/PeriodPostRequestDTO.java
  travel/src/main/java/com/travel/product/dto/response/PeriodOptionsInProduct.java
  travel/src/main/java/com/travel/product/dto/response/ProductDetailGetResponseDTO.java
  travel/src/main/java/com/travel/product/entity/PeriodOption.java
Labels: Type: Refactor, Status: In Progress, Priority: Medium, For: API, For: Backend

#63 Refactor/search 검색 기능, memberId null로 나오는 문제, Enum 값 한글로 출력 수정
  travel/src/main/java/com/travel/order/dto/response/OrderAdminResponseDTO.java
  travel/src/main/java/com/travel/order/dto/response/OrderListAdminResponseDTO.java
  travel/src/main/java/com/travel/order/dto/response/OrderListResponseDTO.java
  travel/src/main/java/com/travel/order/dto/response/OrderResponseDTO.java
  travel/src/main/java/com/travel/order/entity/OrderStatus.java
  travel/src/main/java/com/travel/product/entity/Product.java
  travel/src/main/java/com/travel/product/entity/PurchasedProduct.java
  travel/src/main/java/com/travel/search/controller/SearchController.java
  travel/src/main/java/com/travel/search/dto/request/SortTarget.java
  travel/src/main/java/com/travel/search/dto/response/SearchResultResponseDTO.java
  travel/src/main/java/com/travel/search/service/SearchService.java
Labels: Type: Bug, Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#65 Feature/wishlist
  travel/src/main/java/com/travel/cart/service/impl/CartServiceImpl.java
  travel/src/main/java/com/travel/wishlist/controller/WishlistController.java
  travel/src/main/java/com/travel/wishlist/dto/response/WishlistResponseDTO.java
  travel/src/main/java/com/travel/wishlist/entity/Wishlist.java
  travel/src/main/java/com/travel/wishlist/exception/WishlistException.java
  travel/src/main/java/com/travel/wishlist/exception/WishlistExceptionType.java
  travel/src/main/java/com/travel/wishlist/repository/WishlistRepository.java
  travel/src/main/java/com/travel/wishlist/service/WishlistService.java
  travel/src/main/java/com/travel/wishlist/service/impl/WishlistServiceImpl.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#68 Feature/image S3 이용 이미지 처리 기능 구현
  travel/build.gradle
  travel/src/main/java/com/travel/TravelApplication.java
  travel/src/main/java/com/travel/admin/controller/AdminController.java
  travel/src/main/java/com/travel/cart/entity/Cart.java
  travel/src/main/java/com/travel/image/configuration/AWSConfig.java
  travel/src/main/java/com/travel/image/entity/Image.java
  travel/src/main/java/com/travel/image/exception/ImageException.java
  travel/src/main/java/com/travel/image/exception/ImageExceptionType.java
  travel/src/main/java/com/travel/image/repository/ImageRepository.java
  travel/src/main/java/com/travel/image/service/FileUploadService.java
  travel/src/main/java/com/travel/product/dto/request/ProductPatchRequestDTO.java
  travel/src/main/java/com/travel/product/dto/request/ProductPostRequestDTO.java
  travel/src/main/java/com/travel/product/dto/response/ProductDetailGetResponseDTO.java
  travel/src/main/java/com/travel/product/dto/response/ProductListGetResponseDTO.java
  travel/src/main/java/com/travel/product/entity/Product.java
  travel/src/main/java/com/travel/product/entity/PurchasedProduct.java
  travel/src/main/java/com/travel/product/service/ProductService.java
Labels: Type: Feature, Type: Refactor, Status: In Progress, Priority: Medium, For: API, For: Backend

#69 Feature/delete member
  travel/src/main/java/com/travel/auth/exception/AuthException.java
  travel/src/main/java/com/travel/auth/exception/AuthExceptionType.java
  travel/src/main/java/com/travel/auth/service/MemberService.java
  travel/src/main/java/com/travel/member/controller/MemberController.java
  travel/src/main/java/com/travel/member/dto/requestDTO/DeleteMemberDTO.java
  travel/src/main/java/com/travel/member/service/MemberService.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Feature, Status: In Progress, Priority: Medium, For: API, For: Backend

#73 Feature/image
  travel/src/main/java/com/travel/auth/service/MemberService.java
  travel/src/main/java/com/travel/image/entity/Image.java
  travel/src/main/java/com/travel/image/entity/MemberImage.java
  travel/src/main/java/com/travel/image/entity/ProductImage.java
  travel/src/main/java/com/travel/image/repository/MemberImageRepository.java
  travel/src/main/java/com/travel/image/repository/ProductImageRepository.java
  travel/src/main/java/com/travel/member/controller/MemberController.java
  travel/src/main/java/com/travel/member/entity/Member.java
  travel/src/main/java/com/travel/member/service/MemberService.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
  travel/src/main/java/com/travel/product/dto/response/ProductDetailGetResponseDTO.java
  travel/src/main/java/com/travel/product/entity/Product.java
  travel/src/main/java/com/travel/product/service/ProductService.java
  travel/src/main/java/com/travel/wishlist/entity/Wishlist.java
Labels: Type: Feature, Type: Refactor, Status: In Progress, Priority: Medium, For: API, For: Backend

#74 refactoring: dto, service 추가
  travel/src/main/java/com/travel/auth/dto/request/MemberRequestDto.java
  travel/src/main/java/com/travel/auth/service/MemberService.java
Labels: Type: Refactor, Priority: Low, For: API, For: Backend

#77 Feature/wishlist 위시리스트 추가로 인한 변경, 검색 리스트 정렬 방식 인기순 추가, cors 처리
  travel/src/main/java/com/travel/global/config/SecurityConfig.java
  travel/src/main/java/com/travel/product/entity/Product.java
  travel/src/main/java/com/travel/product/repository/ProductCategoryRepository.java
  travel/src/main/java/com/travel/search/controller/SearchController.java
  travel/src/main/java/com/travel/search/service/SearchService.java
  travel/src/main/java/com/travel/search/service/impl/SearchServiceImpl.java
  travel/src/main/java/com/travel/wishlist/service/impl/WishlistServiceImpl.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#80 Feature/product Product CRUD 완성
  travel/src/main/java/com/travel/admin/controller/AdminController.java
  travel/src/main/java/com/travel/product/dto/request/ProductPatchRequestDTO.java
  travel/src/main/java/com/travel/product/dto/response/CategoriesInProduct.java
  travel/src/main/java/com/travel/product/dto/response/ProductDetailGetResponseDTO.java
  travel/src/main/java/com/travel/product/repository/ProductCategoryRepository.java
  travel/src/main/java/com/travel/product/service/ProductService.java
Labels: Type: Feature, Type: Refactor, Status: In Progress, Priority: Medium, For: API, For: Backend

#85 Refactor #84 버그 수정 및 회원 상세 페이지 조회에서 프로필 이미지 조회 추가
  travel/build.gradle
  travel/src/main/java/com/travel/image/service/FileUploadService.java
  travel/src/main/java/com/travel/member/controller/MemberController.java
  travel/src/main/java/com/travel/member/dto/responseDTO/MemberResponseDTO.java
Labels: Type: Bug, Type: Refactor, Status: In Progress, Priority: Critical, For: API, For: Backend

#89 Feature/qna Post 관련 자식 엔티티 생성, QnA 추가 삭제 구현
  travel/build.gradle
  travel/src/main/java/com/travel/order/dto/response/OrderResponseDTO.java
  travel/src/main/java/com/travel/order/service/impl/OrderServiceImpl.java
  travel/src/main/java/com/travel/post/controller/PostController.java
  travel/src/main/java/com/travel/post/controller/QnAController.java
  travel/src/main/java/com/travel/post/dto/request/QnARequsetDTO.java
  travel/src/main/java/com/travel/post/entity/AnswerPost.java
  travel/src/main/java/com/travel/post/entity/InquiryType.java
  travel/src/main/java/com/travel/post/entity/Post.java
  travel/src/main/java/com/travel/post/entity/QnAPost.java
  travel/src/main/java/com/travel/post/entity/QnAProductPost.java
  travel/src/main/java/com/travel/post/entity/QnAStatus.java
  travel/src/main/java/com/travel/post/entity/ReviewPost.java
  travel/src/main/java/com/travel/post/entity/Scope.java
  travel/src/main/java/com/travel/post/exception/PostException.java
  travel/src/main/java/com/travel/post/exception/PostExceptionType.java
  travel/src/main/java/com/travel/post/repository/PostRepository.java
  travel/src/main/java/com/travel/post/repository/QnAProductRepository.java
  travel/src/main/java/com/travel/post/repository/QnARepository.java
  travel/src/main/java/com/travel/post/service/QnAService.java
  travel/src/main/java/com/travel/post/service/impl/QnAServiceImpl.java
  travel/src/main/java/com/travel/product/entity/Product.java
  travel/src/main/java/com/travel/product/entity/PurchasedProduct.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend, Type: Configuration

#90 Feature/member info, git Ignore
  travel/.gitignore
  travel/src/main/java/com/travel/auth/controller/AuthController.java
  travel/src/main/java/com/travel/auth/service/CustomMemberDetailsService.java
  travel/src/main/java/com/travel/auth/service/MemberService.java
  travel/src/main/java/com/travel/global/config/SecurityConfig.java
  travel/src/main/java/com/travel/member/controller/MemberController.java
  travel/src/main/java/com/travel/member/dto/requestDTO/MemberModifyRequestDTO.java
  travel/src/main/java/com/travel/member/dto/responseDTO/MemberResponseDTO.java
  travel/src/main/java/com/travel/member/entity/Member.java
  travel/src/main/java/com/travel/member/service/MemberService.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Feature, Type: Refactor, Status: In Progress, Priority: Medium, For: API, For: Backend

#93 Feature/qna QnA 리스트 조회(회원, 관리자용), QnA 답변 생성(관리자용) 기능 구현
  travel/src/main/java/com/travel/admin/controller/AdminController.java
  travel/src/main/java/com/travel/global/config/SecurityConfig.java
  travel/src/main/java/com/travel/post/controller/QnAController.java
  travel/src/main/java/com/travel/post/dto/request/QnAAnswerRequestDTO.java
  travel/src/main/java/com/travel/post/dto/request/QnARequestDTO.java
  travel/src/main/java/com/travel/post/dto/response/QnAAdminResponseDTO.java
  travel/src/main/java/com/travel/post/dto/response/QnAResponseDTO.java
  travel/src/main/java/com/travel/post/entity/AnswerPost.java
  travel/src/main/java/com/travel/post/entity/QnAPost.java
  travel/src/main/java/com/travel/post/entity/QnAProductPost.java
  travel/src/main/java/com/travel/post/repository/AnswerRepository.java
  travel/src/main/java/com/travel/post/repository/QnARepository.java
  travel/src/main/java/com/travel/post/service/QnAService.java
  travel/src/main/java/com/travel/post/service/impl/QnAServiceImpl.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend, Type: Configuration

#95 Refactoring/delete member
  travel/src/main/java/com/travel/member/controller/MemberController.java
  travel/src/main/java/com/travel/member/dto/requestDTO/DeleteMemberDTO.java
  travel/src/main/java/com/travel/member/service/MemberService.java
  travel/src/main/java/com/travel/member/service/impl/MemberServiceImpl.java
Labels: Type: Refactor, Status: Completed, Priority: Medium, For: API, For: Backend

#97 Feature/orders 비회원 주문 기능 구현
  travel/src/main/java/com/travel/global/config/SecurityConfig.java
  travel/src/main/java/com/travel/member/entity/Member.java
  travel/src/main/java/com/travel/nonmember/controller/NonMembersController.java
  travel/src/main/java/com/travel/order/dto/request/OrderNonMemberCreateDTO.java
  travel/src/main/java/com/travel/order/service/OrderService.java
  travel/src/main/java/com/travel/order/service/impl/OrderServiceImpl.java
  travel/src/main/java/com/travel/post/controller/QnAController.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend

#103 Feature/orders 결제 수단에 토스페이 추가, Validation 예외 처리, 시큐리티 설정 변경
  travel/src/main/java/com/travel/global/config/SecurityConfig.java
  travel/src/main/java/com/travel/global/exception/CustomExceptionHandler.java
  travel/src/main/java/com/travel/order/entity/PaymentMethod.java
Labels: Type: Feature, Status: Completed, Priority: Medium, For: API, For: Backend, Type: Configuration
